name: Python CI

#Trigger the workflow on Push or Pull event
on:
  push:
    branches:
        - MAIN
  pull_request:
    branches:
        - MAIN

jobs:
    test:
        runs-on: ubuntu-latest

        steps:
            #Step 1: Check out code from Repository
            - name: Checkout Code
              uses: actions/checkout@v2

            #Step2: Setup Python Environment
            - name: Setup Python
              uses: actions/setup-python@v2
              with:
                python-version: '3.8'

            #Step3: Install dependencies
            - name: Install dependencies
              run: |
                python -m pip install --upgrade pip
                pip install -r requirements.txt
